tasks:
  - init: npm install
    command: npm run dev

vscode:
  extensions:
    - esbenp.prettier-vscode@5.1.3:t532ajsImUSrA9N8Bd7jQw==

ports:
  - name: SiliWiz App
    port: 5173
    onOpen: open-browser
